Fix bug 751923 - Failure during event creation [Exception 'TypeError: aItem.calendar.isInvitation is not a function' in calProviderUtils.jsm] (regression). r=mmecca